language: ruby
rvm:
  - 2.2.0
  - 1.9.3
  - jruby-19mode
script:
  - bundle exec rspec --color --pattern test/**/*_test.rb
  - ./bin/modules run example/modular/main.rb
  - ruby example/cycles/main.rb
